[request_definition]
r = role, resource, method

[policy_definition]
p = role, resource, method

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.role, p.role) && keyMatch2(r.resource, p.resource) && regexMatch(r.method, p.method)
